<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</head>
<div class="jumbotron">
    <p>
    show the list of Restaurants by using Google Map API 
    </p>
    <input id="pac-input"  type="text" value="Bangsue" placeholder="Search Box">
    <!-- <p><a class="btn btn-success btn-lg" target="_blank">search </a></p> -->
    <!-- <div id="map"></div> -->
    <div id="map" style="width:100%;height:400px;"></div>

</div>
<div class="container">
  <h2>List of Restaurants</h2>
      
  <table class="table table-dark table-hover">
    <thead>
      <tr>
        <th>Restaurantsname</th>
        <th>Location</th>
      </tr>
    </thead>
    <tbody>
    <?php



    $lat = 13.803011;
    $long = 100.538813;
    $keyword = "Bangsue";

    $url="https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=".$lat.",".$long."&radius=1500&type=restaurant&keyword=".$keyword."&key=AIzaSyDtbkvX3zjP15y_1dQWzoxvAlMLsgJSEuw";
    $headers = array(
        'Content-type: application/json; charset=UTF-8'
    );
    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL,$url);
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_HTTPGET , 1);
    curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
    $response = curl_exec($ch);
    $character = json_decode($response);
//    echo  $response;exit();
    $date = $character->results;
    foreach ($date as $entry){ ?>
      <tr>
        <td><?php print_r($entry->name) ?></td>
        <td><?php print_r($entry->vicinity) ?></td>
      </tr>
    <?php } ?>

      
    </tbody>
  </table>
</div>

<script>


      function initAutocomplete() {
        var map = new google.maps.Map(document.getElementById('map'), {
          center: {lat: 13.803011, lng: 100.538813},
          zoom: 13,
          mapTypeId: 'roadmap'
        });

        // Create the search box and link it to the UI element.
        var input = document.getElementById('pac-input');
        var searchBox = new google.maps.places.SearchBox(input);
        // map.controls[google.maps.ControlPosition.TOP_LEFT].push(input);

        // Bias the SearchBox results towards current map's viewport.
        map.addListener('bounds_changed', function() {
          searchBox.setBounds(map.getBounds());
        });

        var markers = [];
        // Listen for the event fired when the user selects a prediction and retrieve
        // more details for that place.
        searchBox.addListener('places_changed', function() {
          var places = searchBox.getPlaces();

          if (places.length == 0) {
            return;
          }

          // Clear out the old markers.
          markers.forEach(function(marker) {
            marker.setMap(null);
          });
          markers = [];

          // For each place, get the icon, name and location.
          var bounds = new google.maps.LatLngBounds();
          places.forEach(function(place) {
            if (!place.geometry) {
              console.log("Returned place contains no geometry");
              return;
            }
            var icon = {
              url: place.icon,
              size: new google.maps.Size(71, 71),
              origin: new google.maps.Point(0, 0),
              anchor: new google.maps.Point(17, 34),
              scaledSize: new google.maps.Size(25, 25)
            };

            // Create a marker for each place.
            markers.push(new google.maps.Marker({
              map: map,
              icon: icon,
              title: place.name,
              position: place.geometry.location
            }));

            if (place.geometry.viewport) {
              // Only geocodes have viewport.
              bounds.union(place.geometry.viewport);
            } else {
              bounds.extend(place.geometry.location);
            }
          });
          map.fitBounds(bounds);
        });
      }

    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDtbkvX3zjP15y_1dQWzoxvAlMLsgJSEuw&libraries=places&callback=initAutocomplete"
         async defer></script>

<script language="JavaScript">

    function CALLAPI(lat,long,keyword){

        var url="https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=13.803011,100.538813&radius=1500&type=restaurant&keyword=Bangsue&key=AIzaSyDtbkvX3zjP15y_1dQWzoxvAlMLsgJSEuw";
        var headers = array(
            'Content-type: application/json; charset=UTF-8'
        );
        var ch = curl_init();
        curl_setopt(ch, CURLOPT_URL,url);
        curl_setopt(ch, CURLOPT_HTTPHEADER, headers);
        curl_setopt(ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt(ch, CURLOPT_HTTPGET , 1);
        curl_setopt(ch, CURLOPT_SSL_VERIFYPEER, false);
        var response = curl_exec(ch);
        var character = json_decode(response);

    }



</script>

    

